In [1]:
import numpy as np

In [2]:
rank2_array = np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])

In [3]:
print(rank2_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [5]:
x = rank2_array *4

In [6]:
print(x)

[[ 44  48  52  56]
 [ 84  88  92  96]
 [124 128 132 136]]


In [8]:
np.std(x)

32.964627506869647

In [10]:
a_slice = rank2_array[:2,1:3]

In [11]:
print(a_slice)

[[12 13]
 [22 23]]


In [18]:
print(rank2_array[0:2])

[[11 12 13 14]
 [21 22 23 24]]


### One can also create slice of array as shown below ###

In [20]:
a_slice2 = np.array(rank2_array[:2,1:3])

In [21]:
print(a_slice2)

[[12 13]
 [22 23]]


In [22]:
print(rank2_array.shape)

(3, 4)


In [26]:
slice3 = np.array(rank2_array[1:4])

In [27]:
print(slice3)

[[21 22 23 24]
 [31 32 33 34]]


In [32]:
print(rank2_array[:2])

[[11 12 13 14]
 [21 22 23 24]]


In [38]:
y = np.array([[1,2,12],[3,4,13],[5,6,14]])

*** Question; 
If you try to access rows of a 3-by-3 numpy array called “arr” using the command: arr[:2,] How many rows will be returned?  ***

In [39]:
print(y)

[[ 1  2 12]
 [ 3  4 13]
 [ 5  6 14]]


In [40]:
print(y.shape)

(3, 3)


In [41]:
print(y[:2,])

[[ 1  2 12]
 [ 3  4 13]]
