In [1]:
import numpy as np

In [2]:
an_array = np.array([[11,12],[21,22],[31,32]])

Different btw print and just calling the varaible; see below

In [3]:
an_array

array([[11, 12],
       [21, 22],
       [31, 32]])

In [4]:
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [5]:
filter = (an_array > 15)

In [6]:
filter

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [7]:
print(an_array[filter])

[21 22 31 32]


In [8]:
an_array[(an_array > 20)&(an_array < 30)]

array([21, 22])

In [9]:
an_array[(an_array % 2 == 0)]

array([12, 22, 32])

In [11]:
x = an_array[(an_array % 2 == 0)] + 100
print(x)

[112 122 132]
