In [1]:
import numpy as np

In [3]:
ex1 = np.array([11,12])
print(ex1.dtype)

int32


In [4]:
ex2 = np.array([13.0,14.0])
print(ex2.dtype)

float64


Converting int to float datatype

In [5]:
ex3 = np.array([11,12],dtype=np.float64)
print(ex3.dtype)

float64


In [6]:
print(ex3)

[ 11.  12.]


Converting float to int datatype

In [7]:
ex4 = np.array([13.0,14.0],dtype=np.int32)
print(ex4.dtype)

int32


In [8]:
print(ex4)

[13 14]


### Arithmetic array Operations: ###

In [11]:
x = np.array([[111,112],[121,122]],dtype=np.int32)
y = np.array([[211.1,212.1],[221.1,222.1]],dtype=np.float64)

In [12]:
np.add(x,y)

array([[ 322.1,  324.1],
       [ 342.1,  344.1]])

In [13]:
print(x*y)

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]


In [14]:
print(y-x)

[[ 100.1  100.1]
 [ 100.1  100.1]]


In [15]:
print(y/x)

[[ 1.9018018   1.89375   ]
 [ 1.82727273  1.8204918 ]]


In [19]:
sqrt_y = np.sqrt(y)
print(sqrt_y)

[[ 14.52928078  14.56365339]
 [ 14.86943173  14.90301983]]


In [21]:
sqrt_x = np.sqrt(x)
print(sqrt_x)

[[ 10.53565375  10.58300524]
 [ 11.          11.04536102]]


In [22]:
np.add(sqrt_y, sqrt_x)

array([[ 25.06493453,  25.14665863],
       [ 25.86943173,  25.94838085]])