In [2]:
#this ndarray basics

import numpy as np
an_array = np.array([3,33,333])
print(type(an_array))


<class 'numpy.ndarray'>


In [3]:
print(an_array.shape)

(3,)


In [4]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [5]:
an_array[0] = 88

In [6]:
print(an_array[0])

88


In [7]:
print(an_array[0],an_array[1],an_array[2])

88 33 333


### Creating a rank 2 arrays:

In [8]:
rank2_array = np.array([[11,12,13],[21,22,23]])

In [9]:
print(rank2_array.shape)

(2, 3)


In [10]:
print(rank2_array)

[[11 12 13]
 [21 22 23]]


In [11]:
x = rank2_array * 2

In [12]:
print(x)

[[22 24 26]
 [42 44 46]]


In [14]:
print("the shape of our rank 2 array, row 2 and column 3",rank2_array)

the shape of our rank 2 array, row 2 and column 3 [[11 12 13]
 [21 22 23]]


In [16]:
ex1 = np.zeros((3,3))

In [17]:
print(ex1)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [19]:
ex2 = np.eye(4,4)

In [20]:
print(ex2)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [21]:
np.mean(x)

34.0