In [1]:
import numpy as np

In [6]:
x = np.zeros((4,3), dtype=np.float64)
print(x)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [8]:
add_row = np.array([1,0,2])
print(add_row)


[1 0 2]


In [9]:
y = x+add_row

In [11]:
print(y)

[[ 1.  0.  2.]
 [ 1.  0.  2.]
 [ 1.  0.  2.]
 [ 1.  0.  2.]]


In [14]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

In [15]:
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [16]:
y2 = x+add_cols

In [17]:
y2

array([[ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

Ansering Booadcasting Question:

In [18]:
a = np.array([[0,0],[0,0]])
b1 = np.array([1,1])
b2 = 1
print(a)
print(b1)

[[0 0]
 [0 0]]
[1 1]


In [19]:
x = a+b1

In [20]:
print(x)

[[1 1]
 [1 1]]


In [21]:
x2 = a+b2

In [22]:
x2

array([[1, 1],
       [1, 1]])