In [1]:
import numpy as np

In [3]:
x = np.random.randn(5,3)

In [4]:
print(x)

[[ 0.52525764  0.09688224  0.09671485]
 [-0.4609803  -0.07330925  2.1809776 ]
 [ 0.24836416 -0.99544401 -0.84585031]
 [ 0.05841018  0.20969717  0.6287182 ]
 [ 0.85398226 -0.78587942  1.29214945]]


In [6]:
print(x.sum())

3.02969042494


In [7]:
print(x.sum(axis =1))

[ 0.71885472  1.64668804 -1.59293017  0.89682555  1.36025228]


In [8]:
print(x.sum(axis =0))

[ 1.22503393 -1.54805327  3.35270977]


In [9]:
print(x.mean())

0.201979361663


In [10]:
print(x.std())

0.811768061308


In [ ]:
y = np.random.randn