In [23]:
import numpy as np
from scipy import stats

In [4]:
x = 10 * np.random.randn(3,5)
print(x)

[[  9.29766402  -0.60452984  13.63842304  -9.78132897   5.09109068]
 [ -0.91249909   7.80833322 -11.5506309   -6.2786164   14.96192149]
 [  4.42156027  -8.36023641  -5.75520424  11.4453681   17.56778671]]


In [8]:
print(x.mean())

2.73260677835


In [9]:
print(x.mean(axis = 1))

[ 3.52826378  0.80570166  3.86385489]


In [15]:
print(x.mean(axis = 0))

[  4.2689084   -0.38547768  -1.2224707   -1.53819242  12.54026629]


In [17]:
print(x.sum())

40.9891016753


In [18]:
print(x.sum(axis = 1))
print(x.sum(axis = 0))

[ 17.64131892   4.02850832  19.31927443]
[ 12.8067252   -1.15643303  -3.6674121   -4.61457727  37.62079888]


In [24]:
stats.describe(x)

DescribeResult(nobs=3, minmax=(array([ -0.91249909,  -8.36023641, -11.5506309 ,  -9.78132897,   5.09109068]), array([  9.29766402,   7.80833322,  13.63842304,  11.4453681 ,  17.56778671])), mean=array([  4.2689084 ,  -0.38547768,  -1.2224707 ,  -1.53819242,  12.54026629]), variance=array([  26.07933464,   65.3916489 ,  174.03136458,  129.49688167,
         43.31529642]), skewness=array([-0.05486591,  0.0497284 ,  0.55670316,  0.63248672, -0.58445263]), kurtosis=array([-1.5, -1.5, -1.5, -1.5, -1.5]))

In [25]:
print(np.median(x,axis=1))

[ 5.09109068 -0.91249909  4.42156027]


In [26]:
print(np.median(x,axis=0))

[  4.42156027  -0.60452984  -5.75520424  -6.2786164   14.96192149]


### Sorting Array: ###

In [28]:
unsort = np.random.randn(10)
print(unsort)

[-0.17135935 -1.35983965  0.24793207  0.98912353  1.0401871   0.06158045
 -0.6163766  -0.08223103  0.2321912  -1.67218582]


In [31]:
sorted = np.array(unsort)
sorted.sort()
print(sorted)

[-1.67218582 -1.35983965 -0.6163766  -0.17135935 -0.08223103  0.06158045
  0.2321912   0.24793207  0.98912353  1.0401871 ]


** Printing unique values in array: **

In [32]:
xzy = np.array([1,2,2,2,1,3,5,5,5,6,10])

In [33]:
np.unique(xzy)

array([ 1,  2,  3,  5,  6, 10])

In [34]:
y1 = np.array(['Desk','chair','bulb'])
y2 = np.array(['Lamp','chair','bulb'])
print(y1,y2)

['Desk' 'chair' 'bulb'] ['Lamp' 'chair' 'bulb']


In [40]:
print(np.intersect1d(y1,y2))

['bulb' 'chair']


In [41]:
print(np.union1d(y1,y2))

['Desk' 'Lamp' 'bulb' 'chair']


In [42]:
print(np.setdiff1d(y1,y2))

['Desk']


In [43]:
print(np.in1d(y1,y2))

[False  True  True]
